package com.fau.amos.team2.WoundManagement;

import com.vaadin.addon.touchkit.ui.NavigationView;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class LoggedInView extends NavigationView {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private Button logoutbutton;

	@SuppressWarnings("deprecation")
	public LoggedInView(String benutzer) {
		VerticalLayout mainLayout = new VerticalLayout();

		// label_1
		label_1 = new Label();

		label_1.setValue("Hi, you are logged in! " + benutzer);
		mainLayout.addComponent(label_1);
		
		// logoutbutton
		logoutbutton = new Button();
		logoutbutton.setCaption("Ich will wieder weg = logout");

		// Falls loggout button gedrueckt wird, soll der User wieder zum
		// Login-View

		logoutbutton.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				
				getSession().setAttribute("user", null);
				
				Notification.show("Tschuess!");

				NavigationView next2 = new LoginView();
				getNavigationManager().navigateTo(next2);
			}
		});
		mainLayout.addComponent(logoutbutton);

		addComponent(mainLayout);

	}



	
}
