package com.fau.amos.team2.WoundManagement;

import com.fau.amos.team2.WoundManagement.provider.EmployeeProvider;
import com.vaadin.addon.touchkit.ui.NavigationView;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Notification;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

/**
 * The View that is shown in order to login.
 * 
 * @author ???
 */
@SuppressWarnings("serial")
public class LoginView extends NavigationView {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button loginButton;
	@AutoGenerated
	private PasswordField passwordField;
	@AutoGenerated
	private TextField usernameField;

	/**
	 * Creates an instance of LoginView in order to login.
	 * 
	 * If user login correct creates a new View
	 * @see com.fau.amos.team2.WoundManagement.LoggedInView
	 */
	@SuppressWarnings("deprecation")
	public LoginView() {
		VerticalLayout mainLayout = new VerticalLayout();

		usernameField = new TextField();
		usernameField.setCaption("Benutzername:");
		mainLayout.addComponent(usernameField);

		passwordField = new PasswordField();
		passwordField.setCaption("Passwort:");
		mainLayout.addComponent(passwordField);

		loginButton = new Button();
		loginButton.setCaption("Login");
		loginButton.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				if(validateData()) {
					Notification.show("Logge ein, bitte warten..." + usernameField.getValue());
					
					Object id = EmployeeProvider.getInstance()
							.getLoginID(usernameField.getValue(), passwordField.getValue());
					
					NavigationView next = new LoggedInView(id);
					getNavigationManager().navigateTo(next);
				} 
				else 
				{
					Notification.show("Falsche Daten, bitte neu eingeben! Danke!");

					passwordField.setValue("");
					usernameField.setValue("");
				}
			}
		});
		mainLayout.addComponent(loginButton);

		addComponent(mainLayout);
	}
	/**
	 * Validate user input with data in the database
	 * 
	 * @return true if user fits password in the database, false otherwise
	 */
	private boolean validateData() {
		String username = usernameField.getValue();
		String password = passwordField.getValue();
		
		if(EmployeeProvider.getInstance().getLogin(username, password)) {
			return true;
		}
		return false;
	}

}