package simonlogin;

import com.vaadin.addon.touchkit.ui.NavigationView;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.Navigator;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class LoginView extends NavigationView {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button loginbutton;
	@AutoGenerated
	private PasswordField passwordfield;
	@AutoGenerated
	private TextField usernamefield;

	public LoginView() {
		// buildMainLayout();
		// setCompositionRoot(mainLayout);
		// common part: create layout
		VerticalLayout mainLayout = new VerticalLayout();

		// mainLayout.addComponent(new TextField("Name"));
		usernamefield = new TextField();
		usernamefield.setCaption("Benutzername:");

		mainLayout.addComponent(usernamefield);

		// passwordfield
		passwordfield = new PasswordField();
		passwordfield.setCaption("Passwort:");

		mainLayout.addComponent(passwordfield);

		loginbutton = new Button();
		loginbutton.setCaption("Login");

		// Login wird bei klick auf butten ausgefuehrt, ueber die
		// validateData-Methode
		loginbutton.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				validateData();
			}
		});
		mainLayout.addComponent(loginbutton);

		addComponent(mainLayout);

	}

	private void validateData() {

		// Wenn button geklickt wird, ueberpruefen ob richtige daten eingegeben
		// wurden
		// To DO: datenbankqueries verringern mit hilfe von einer "isvalid"
		// funktion

		if ((usernamefield.getValue().equals("Simon"))
				&& (passwordfield.getValue().equals("1234"))) {

			getSession().setAttribute("user", usernamefield.getValue());

			String benutzer = String.valueOf(getSession().getAttribute("user"));

		
			Notification.show("Logge ein, bitte warten..." + benutzer);

			NavigationView next = new LoggedIn(benutzer);
			getNavigationManager().navigateTo(next);
			
		
		} else {

			Notification.show("Falsche Daten, bitte neu eingeben! Danke!");

			this.passwordfield.setValue("");
			this.usernamefield.setValue("");
		}
	}

}