function de_fau_cs_amos_gwt_AppWidgetSet(){var Y='',V=' top: -1000px;',tb='" for "gwt:onLoadErrorFn"',rb='" for "gwt:onPropertyErrorFn"',cb='");',ub='#',Mb='.cache.js',wb='/',Cb='//',Jb='85D7F226159952B9E0EBE92AAF7F1CF7',Lb=':',Kb=':1',lb='::',Qb=':moduleBase',X='<!doctype html>',Z='<html><head><\/head><body><\/body><\/html>',ob='=',vb='?',qb='Bad handler "',W='CSS1Compat',ab='Chrome',_='DOMContentLoaded',Q='DUMMY',Pb='__gwtDevModeHook:de.fau.cs.amos.gwt.AppWidgetSet',Eb='android 2.',Fb='android2',Bb='base',zb='baseUrl',L='begin',R='body',K='bootstrap',yb='clear.cache.gif',nb='content',O='de.fau.cs.amos.gwt.AppWidgetSet',Ib='de.fau.cs.amos.gwt.AppWidgetSet.devmode.js',Ab='de.fau.cs.amos.gwt.AppWidgetSet.nocache.js',kb='de.fau.cs.amos.gwt.AppWidgetSet::',Ob='end',bb='eval("',M='gwt.codesvr.de.fau.cs.amos.gwt.AppWidgetSet=',N='gwt.codesvr=',sb='gwt:onLoadErrorFn',pb='gwt:onPropertyErrorFn',mb='gwt:property',hb='head',S='iframe',xb='img',eb='javascript',T='javascript:""',Nb='loadExternalRefs',ib='meta',gb='moduleRequested',fb='moduleStartup',jb='name',U='position:absolute; width:0; height:0; border:none; left: -1000px;',db='script',Hb='selectingPermutation',P='startup',Gb='std',$='undefined',Db='webkitvariant';var o=window;var p=document;r(K,L);function q(){var a=o.location.search;return a.indexOf(M)!=-1||a.indexOf(N)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:O,sessionId:o.__gwtStatsSessionId,subSystem:P,evtGroup:a,millis:(new Date).getTime(),type:b})}}
de_fau_cs_amos_gwt_AppWidgetSet.__sendStats=r;de_fau_cs_amos_gwt_AppWidgetSet.__moduleName=O;de_fau_cs_amos_gwt_AppWidgetSet.__errFn=null;de_fau_cs_amos_gwt_AppWidgetSet.__moduleBase=Q;de_fau_cs_amos_gwt_AppWidgetSet.__softPermutationId=0;de_fau_cs_amos_gwt_AppWidgetSet.__computePropValue=null;de_fau_cs_amos_gwt_AppWidgetSet.__getPropMap=null;de_fau_cs_amos_gwt_AppWidgetSet.__gwtInstallCode=function(){};de_fau_cs_amos_gwt_AppWidgetSet.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[O]={moduleName:O};var v;function w(){y();return v}
function x(){y();return v.getElementsByTagName(R)[0]}
function y(){if(v){return}var a=p.createElement(S);a.src=T;a.id=O;a.style.cssText=U+V;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==W?X:Y;v.write(b+Z);v.close()}
function z(k){function l(a){function b(){if(typeof p.readyState==$){return typeof p.body!=$&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(_,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(_,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=x();var f=w();var g;if(navigator.userAgent.indexOf(ab)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(bb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(cb));g=f.createElement(db);g.language=eb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(db);g.language=eb;g.text=c[i];e.appendChild(g);d(e,g)}}}
de_fau_cs_amos_gwt_AppWidgetSet.onScriptDownloaded=function(a){l(function(){m(a)})};r(fb,gb);var n=p.createElement(db);n.src=k;p.getElementsByTagName(hb)[0].appendChild(n)}
de_fau_cs_amos_gwt_AppWidgetSet.__startLoadingFragment=function(a){return C(a)};de_fau_cs_amos_gwt_AppWidgetSet.__installRunAsyncCode=function(a){var b=x();var c=w().createElement(db);c.language=eb;c.text=a;b.appendChild(c);b.removeChild(c)};function A(){var c={};var d;var e;var f=p.getElementsByTagName(ib);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(jb),k;if(j){j=j.replace(kb,Y);if(j.indexOf(lb)>=0){continue}if(j==mb){k=i.getAttribute(nb);if(k){var l,m=k.indexOf(ob);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=Y}c[j]=l}}else if(j==pb){k=i.getAttribute(nb);if(k){try{d=eval(k)}catch(a){alert(qb+k+rb)}}}else if(j==sb){k=i.getAttribute(nb);if(k){try{e=eval(k)}catch(a){alert(qb+k+tb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;de_fau_cs_amos_gwt_AppWidgetSet.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(ub);if(b==-1){b=a.length}var c=a.indexOf(vb);if(c==-1){c=a.length}var d=a.lastIndexOf(wb,Math.min(c,b));return d>=0?a.substring(0,d+1):Y}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(xb);b.src=a+yb;a=e(b.src)}return a}
function g(){var a=t(zb);if(a!=null){return a}return Y}
function h(){var a=p.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Ab)!=-1){return e(a[b].src)}}return Y}
function i(){var a=p.getElementsByTagName(Bb);if(a.length>0){return a[a.length-1].href}return Y}
function j(){var a=p.location;return a.href==a.protocol+Cb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==Y){k=h()}if(k==Y){k=i()}if(k==Y&&j()){k=e(p.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return de_fau_cs_amos_gwt_AppWidgetSet.__moduleBase+a}
function D(){var f=[];var g;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[Db]=function(){{var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Eb)!=-1){return Fb}return Gb}};i[Db]={android2:0,std:1};s=function(a,b){return b in i[a]};de_fau_cs_amos_gwt_AppWidgetSet.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};de_fau_cs_amos_gwt_AppWidgetSet.__computePropValue=k;o.__gwt_activeModules[O].bindings=de_fau_cs_amos_gwt_AppWidgetSet.__getPropMap;r(K,Hb);if(q()){return C(Ib)}var l;try{h([Fb],Jb);h([Gb],Jb+Kb);l=f[k(Db)];var m=l.indexOf(Lb);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}de_fau_cs_amos_gwt_AppWidgetSet.__softPermutationId=g;return C(l+Mb)}
function E(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(Nb,L);r(Nb,Ob)}
A();de_fau_cs_amos_gwt_AppWidgetSet.__moduleBase=B();u[O].moduleBase=de_fau_cs_amos_gwt_AppWidgetSet.__moduleBase;var F=D();if(o){o.__gwt_activeModules[O].canRedirect=true}var G=Pb;var H=o.sessionStorage[G];if(H&&!o[G]){o[G]=true;var I=p.createElement(db);o[G+Qb]=B();I.src=H;var J=p.getElementsByTagName(hb)[0];J.insertBefore(I,J.firstElementChild||J.children[0]);return false}E();r(K,Ob);z(F);return true}
de_fau_cs_amos_gwt_AppWidgetSet.succeeded=de_fau_cs_amos_gwt_AppWidgetSet();