/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.fau.amos.team2.WoundManagement;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_settings=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int screen=0x7f020002;
    }
    public static final class id {
        public static final int action_settings=0x7f060000;
    }
    public static final class menu {
        public static final int mainmenu=0x7f050000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
    public static final class xml {
        public static final int config=0x7f030000;
        public static final int preferences=0x7f030001;
    }
}
